---
version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
    time: "03:00"
  groups:
    version-updates:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "03:00"
  groups:
    version-updates:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: gitsubmodule
  directory: /
  schedule:
    interval: daily
    time: "03:00"
  groups:
    version-updates:
      applies-to: version-updates
      patterns:
        - "*"
